/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.crudestudiante.view;
import com.mycompany.crudestudiante.controller.ControlEstudiante;
import com.mycompany.crudestudiante.controller.ServicioEstudiante;
import com.mycompany.crudestudiante.controller.DecoratorValidacion;
import com.mycompany.crudestudiante.controller.DecoratorNotificacion;
import com.mycompany.crudestudiante.controller.DecoratorValidacionMayorEdad;
import com.mycompany.crudestudiante.controller.ServicioMateria;
import com.mycompany.crudestudiante.controller.FachadaEstadisticas;
import com.mycompany.crudestudiante.model.Estudiante;
import com.mycompany.crudestudiante.model.Materia;
import com.mycompany.crudestudiante.model.CatalogoMaterias;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Alexander
 */
public class FrmEstudiante extends javax.swing.JPanel {
    
    // Control base con decorators
    private ControlEstudiante controladorBase = new ControlEstudiante();
    
    // Control con decorators: Validación Mayor de Edad → Validación → Notificaciones
    private ServicioEstudiante control = new DecoratorNotificacion(
        new DecoratorValidacion(
            new DecoratorValidacionMayorEdad(
                controladorBase
            )
        )
    );
    
    // Servicios que comparten el mismo controlador
    private ServicioMateria servicioMateria = new ServicioMateria(controladorBase);
    private FachadaEstadisticas estadisticas = new FachadaEstadisticas(controladorBase);

    /**
     * Creates new form FrmEstudiante
     */
    public FrmEstudiante() {
      initComponents();
        configurarTabla();
        configurarComboMaterias();
        mostrarTabla(); 
    }

    private void configurarComboMaterias() {
        cmbMaterias.removeAllItems();
        List<Materia> materias = CatalogoMaterias.obtenerTodasLasMaterias();
        for (Materia m : materias) {
            cmbMaterias.addItem(m);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();
        btnMostrarTodo = new javax.swing.JButton();
        cmbMaterias = new javax.swing.JComboBox<>();
        btnAsignarMateria = new javax.swing.JButton();
        btnEliminarMateria = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");
        jLabel2.setText("Nombre");
        jLabel3.setText("Edad");
        jLabel4.setText("Materia");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Edad", "Materias"
            }
        ));
        jScrollPane1.setViewportView(tblEstudiantes);

        btnMostrarTodo.setText("Mostrar Todo");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });
        
        btnAsignarMateria.setText("Asignar Materia");
        btnAsignarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarMateriaActionPerformed(evt);
            }
        });
        
        btnEliminarMateria.setText("Eliminar Materia");
        btnEliminarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMateriaActionPerformed(evt);
            }
        });
        
        btnEstadisticas.setText("Ver Estadísticas");
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(jLabel2)
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAsignarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarTodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAsignarMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstadisticas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
            new String[]{"ID", "Nombre", "Edad", "Materias"},
            0
        );
        tblEstudiantes.setModel(modelo);
    }
    private void mostrarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblEstudiantes.getModel();
        modelo.setRowCount(0); // Limpiar

        List<Estudiante> estudiantes = control.obtenerTodos();
        for (Estudiante e : estudiantes) {
            String materias = e.getMaterias().isEmpty() ? "Sin materias" :
                String.join(", ", e.getMaterias().stream()
                    .map(Materia::getNombre)
                    .toArray(String[]::new));
            
            modelo.addRow(new Object[]{
                e.getId(),
                e.getNombre(),
                e.getEdad(),
                materias
            });
        }
    }
   
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            int id = Integer.parseInt(txtId.getText());
            String mensaje = control.borrarEstudiante(id);
            JOptionPane.showMessageDialog(this, mensaje);
            mostrarTabla();
            txtId.setText("");
            txtNombre.setText("");
            txtEdad.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: El ID debe ser un número.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
          try {
        int id        = Integer.parseInt(txtId.getText());
        String nombre = txtNombre.getText();
        int edad      = Integer.parseInt(txtEdad.getText());

        String mensaje = control.actualizarEstudiante(id, nombre, edad);
        JOptionPane.showMessageDialog(this, mensaje);
        mostrarTabla();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: Revisa que ID y Edad sean números.");
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
       mostrarTabla(); // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
         try {
            int id = Integer.parseInt(txtId.getText());
            String nombre = txtNombre.getText();
            int edad = Integer.parseInt(txtEdad.getText());

            // Llamada a la capa de Control
            String mensaje = control.registrarEstudiante(id, nombre, edad);
            JOptionPane.showMessageDialog(this, mensaje);
            
            mostrarTabla(); // Refrescar la vista
            txtId.setText("");
            txtNombre.setText("");
            txtEdad.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Revisa que ID y Edad sean números.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed
    
    private void btnAsignarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarMateriaActionPerformed
        try {
            int idEstudiante = Integer.parseInt(txtId.getText());
            Materia materia = (Materia) cmbMaterias.getSelectedItem();
            
            if (materia == null) {
                JOptionPane.showMessageDialog(this, "Error: Selecciona una materia.");
                return;
            }
            
            String mensaje = servicioMateria.asignarMateria(idEstudiante, materia);
            JOptionPane.showMessageDialog(this, mensaje);
            mostrarTabla();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: El ID debe ser un número.");
        }
    }//GEN-LAST:event_btnAsignarMateriaActionPerformed
    
    private void btnEliminarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMateriaActionPerformed
        try {
            int idEstudiante = Integer.parseInt(txtId.getText());
            Materia materia = (Materia) cmbMaterias.getSelectedItem();
            
            if (materia == null) {
                JOptionPane.showMessageDialog(this, "Error: Selecciona una materia.");
                return;
            }
            
            String mensaje = servicioMateria.eliminarMateria(idEstudiante, materia);
            JOptionPane.showMessageDialog(this, mensaje);
            mostrarTabla();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: El ID debe ser un número.");
        }
    }//GEN-LAST:event_btnEliminarMateriaActionPerformed
    
    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        String reporte = estadisticas.obtenerReporteGeneral();
        JOptionPane.showMessageDialog(this, reporte, "Estadísticas del Sistema", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEstadisticasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JButton btnAsignarMateria;
    private javax.swing.JButton btnEliminarMateria;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JComboBox<Materia> cmbMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEstudiantes;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
